# Generated by Django 4.2.7 on 2023-11-14 17:52

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
