# Generated by Django 4.2.7 on 2023-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PB', 'Public'), ('PV', 'Private')], default='PV', max_length=2),
        ),
    ]
