# Generated by Django 4.2.7 on 2023-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private'), ('DEL', 'Deleted')], default='PRI', max_length=3),
        ),
    ]
